name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t my-gradio-app .

    - name: Run tests
      run: |
        # Assuming you have tests in a `tests` directory
        docker run --rm my-gradio-app python -m unittest discover -s tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Server
      run: |
        # Add your deployment commands here
        echo "Deploying to server..."
        # Example: ssh user@your-server "docker pull my-gradio-app && docker run -d -p 7860:7860 my-gradio-app"
